// BSS-Helpers JS engine
// Loaded once by src/Control Pages/BSS-Lib/40-BSS-Lib-LoadHelpers.txt, generated by tools/wrap-js.sh.
// Dark Matter JS is old ES5: use var and plain functions, no let/const/import.
// Do not put closing parentheses inside comments: older DM versions end the block there.
// Variables here persist until the engine is removed.

var running = 0;

// Send a DM script line and echo it to Event Viewer > JavaScript Processor
function dm(s) {
    DigitalSky.SendScript(s);
    DigitalSky.LogMessage(s);
}

// Wait n seconds. Note: the Playlist renderer counts JS waits as 0 s
function wait(n) {
    DigitalSky.Wait(n);
}

function getCameraAltitude() {
    return DigitalSky.GetAssetInstance("Camera").GetPropertyInstance("Altitude").Value;
}

// Logarithmic fly-in or fly-out: multiply camera altitude by factor every step seconds
// until target altitude is reached. factor < 1 flies in, factor > 1 flies out.
// Example button call, fly in to 1e7 m shrinking 3% every 0.1 s:
//   JS BSS-Helpers.Execute with "LogFly 1e7, 0.97, 0.1" -- see src/Snippets/log-fly-in.txt
function LogFly(target, factor, step) {
    running = 1;
    var alt = getCameraAltitude();
    while (running) {
        alt = alt * factor;
        if ((factor < 1 && alt <= target) || (factor > 1 && alt >= target)) {
            dm("Scene Camera.Altitude=" + target + " [" + step + "]");
            break;
        }
        dm("Scene Camera.Altitude=" + alt + " [" + step + "]");
        wait(step);
    }
    running = 0;
}

// Stop any running loop. Called by BSS-Lib-ResetSoft
function Stop() {
    running = 0;
}
