#!/usr/bin/env bash
# Wrap a JS engine source file into a Dark Matter loader button script.
#
#   tools/wrap-js.sh src/JavaScript/BSS-Helpers.js BSS-Helpers \
#       > "src/Control Pages/BSS-Lib/40-BSS-Lib-LoadHelpers.txt"
#
# The generated header puts line 1 of the .js on line 12 of the button. If a JS error
# line number in Event Viewer doesn't match the .js, try subtracting 11, and remember
# DM strips blank lines (count non-blank lines).
set -euo pipefail

src=${1:?usage: wrap-js.sh <file.js> <EngineName>}
engine=${2:?usage: wrap-js.sh <file.js> <EngineName>}
base=$(basename "$src")

# Warn about patterns that break DM's JS block
if grep -nE '//.*\)' "$src" >&2; then
    echo "WARNING: ')' inside a // comment above may terminate the JS block in older DM." >&2
fi
if grep -vE '^\s*//' "$src" | grep -nE '\b(let|const)\b' >&2; then
    echo "WARNING: let/const found; DM's JS engine may need var." >&2
fi

cat <<EOF
;=== BSS-Lib-Load${engine#BSS-} ===
; Page: BSS-Lib   Button: "Load ${engine}"   Length: ~0.5 s
; GENERATED by tools/wrap-js.sh from src/JavaScript/${base} -- edit the .js, not this file.
Control Text="Loading ${engine}..."
JS Remove(${engine})
+0.1
JS Add(${engine})
+0.1
; (Event Viewer JS line N is about line N-11 of the .js source)
;
JS ${engine}.Execute(@"
EOF
cat "$src"
cat <<EOF
@")
+0.1
Control Text="Load ${engine}"
EOF
